// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM8qe2W2oGxuNu08W0-af_WHEDwS5vcd4',
    appId: '1:306466132750:android:cdb1164eafd5ea70557d5f',
    messagingSenderId: '306466132750',
    projectId: 'instagram-67e28',
    databaseURL: 'https://instagram-67e28-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-67e28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeUfDdFRbbj2z3GZUn6X2j-C6A688Z5QQ',
    appId: '1:306466132750:ios:b6f28271cf02139d557d5f',
    messagingSenderId: '306466132750',
    projectId: 'instagram-67e28',
    databaseURL: 'https://instagram-67e28-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-67e28.appspot.com',
    androidClientId: '306466132750-vutmevdgp7cdkcpgal73a9ipvot236pl.apps.googleusercontent.com',
    iosClientId: '306466132750-br9gka8o9hdv1uiv02lub9cp31ak5urm.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
